### ISSUE TITLE
Navigation bar and links not matching the preview picture

### ISSUE THREAD

**Issue by ghost** [nikolaknot/site-project#6]
Navigation bar and it's links are not quite like on the provided image. Style it to look as similar as possible.

Some of the issues:
- nav links are not occupying li fully, apply padding on "a" elements not on "li"
- match the correct height of links and navbar with correct padding/line-height values (preferably global line-height rule)
- nav links borders are different
- shadow on text
- hover styles for nav links

**Comment by nikolaknot** [comment]
Fixed:
- nav links are fully occupied
  -borders
  -shados is put on text
  -hover styles on nav links done
